### ISSUE TITLE
ChangeWindows uses a loopback js url for production environment

### ISSUE THREAD

**Issue by hv0905** [ChangeWindows/ChangeWindows#174]
![image](https://github.com/ChangeWindows/ChangeWindows/assets/29349119/60d6680e-0333-4eda-a5c6-4b8f0ab52e61)
From source of https://changewindows.org/timeline

**Comment by SergiusTheBest** [comment]
Yeap, https://changewindows.org/timeline is currently broken, however https://preview.changewindows.org/timeline works.

The project is awesome. Thank you, @Studio384 !

**Comment by Studio384** [comment]
This should be fixed now
