### ISSUE TITLE
Release Preview showing as just "Release"

### ISSUE THREAD

**Issue by Rexogamer** [ChangeWindows/ChangeWindows#64]
MS haven't renamed the RP channel, so this is a (somewhat minor) error.

**Comment by Studio384** [comment]
The name has been updated for the releases that showed "Release" to match all the others as "Preview". Thanks for the keen eye.

Of course, we can't show the full "Release Preview Channel" name in all situations because that is way to long. We've chosen to abbreviate to just "Preview".

**Comment by Rexogamer** [comment]
That's perfect, thanks :)
