### ISSUE TITLE
Crash when navigating to platforms in Firefox

### ISSUE THREAD

**Issue by Studio384** [ChangeWindows/ChangeWindows#76]
https://twitter.com/Brawl345/status/1392208491985707016/photo/1

**Comment by Studio384** [comment]
Thanks to Brawl345 for noticing this. Since this was kinda a big problem, I've rolled out a fix for this to 7.0.1. The other fixes in 7.0.2 should be released later today.

**Comment by Brawl345** [comment]
Works now, thanks!
