### ISSUE TITLE
`markdown-to-jsx` crashes when `null` is passed as its child

### ISSUE THREAD

**Issue by wojtekmaj** [ChangeWindows/ChangeWindows#77]
https://changewindows.org/releases/windows-10-may-2021-update

```
TypeError: Cannot read property 'replace' of null
```

Cause (minified):

```
            return n(function(e) {
              return e.replace(w, "\n").replace(C, "").replace(W, "    ")
            }(e), t)
```

Looks like it's a neatly minified part of `markdown-to-jsx`:

https://github.com/probablyup/markdown-to-jsx/blob/6afc77c9cea2c2ef53f7bf2b85e7cf5e41f42136/index.tsx#L682-L684

https://github.com/probablyup/markdown-to-jsx/blob/6afc77c9cea2c2ef53f7bf2b85e7cf5e41f42136/index.tsx#L571-L576

**Comment by wojtekmaj** [comment]
I have determined that for this release the following is returned:

```
{
  "name": "Windows 10 May 2021 Update",
  "changelog": null,
  "version": "21H1",
  "codename": "Vibranium 3"
}
```

and indeed, null crashes Markdown:

https://codesandbox.io/s/markdown-to-jsx-crash-on-null-1t3lh

**Comment by wojtekmaj** [comment]
Also reported to `markdown-to-jsx` as I don't think that was supposed to happen: https://github.com/probablyup/markdown-to-jsx/issues/392

**Comment by Studio384** [comment]
Yep, I saw this issue happened before, forgot to fix it. Thanks for reporting. It is now "fixed" by adding an empty changelog to the milestone. I'm probably swapping the markdown parser out for something else.

**Comment by wojtekmaj** [comment]
Personally I've been using react-markdown and I'm pretty happy with it
