### ISSUE TITLE
Can't Sign in or make a new account

### ISSUE THREAD

**Issue by JTDaddy17** [ChangeWindows/ChangeWindows#89]
I use to have an account back with the Viv update, now the latest version doesn't recognize my account, to make matters worse there's no "create new account" option. Please fix this.

**Comment by Rexogamer** [comment]
I wasn't sure if accounts were meant to be invite only or something, but I couldn't log in, recover or create either.

**Comment by Studio384** [comment]
There is no point in having an account, so they were removed. You can actually make an account today, its just hidden. There is currently no intend to make this a front-facing feature however. Not as long as I can't add value to having an account for non-editors in the first place.

**Comment by Rexogamer** [comment]
One potential benefit for non-editors could be email notifications for selected rings (eg I could opt into notifications when new Insider Dev builds release)? But yeah, fair enough.
